import 'package:flutter/material.dart';
import 'package:intl/intl.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import '../../data/local/app_database.dart';
import '../../domain/logic/settlement_calculator.dart';

class FinalReceiptScreen extends StatelessWidget {
  final Tour tour;
  final List<User> users;
  final List<Expense> expenses;
  final List<ExpenseSplit> splits;
  final List<Settlement> settlementInstructions;

  const FinalReceiptScreen({
    super.key,
    required this.tour,
    required this.users,
    required this.expenses,
    required this.splits,
    required this.settlementInstructions,
  });

  Future<void> _printReceipt() async {
    final pdf = pw.Document();

    final totalCost = expenses.fold(0.0, (sum, e) => sum + e.amount);

    pdf.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4,
        build: (pw.Context context) {
          return pw.Padding(
            padding: const pw.EdgeInsets.all(24),
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Center(
                  child: pw.Text('TOUR COST RECEIPT', style: pw.TextStyle(fontSize: 24, fontWeight: pw.FontWeight.bold)),
                ),
                pw.SizedBox(height: 8),
                pw.Center(
                  child: pw.Text(tour.name, style: pw.TextStyle(fontSize: 18)),
                ),
                pw.Center(
                  child: pw.Text(
                    tour.startDate == null 
                        ? 'Active Adventure' 
                        : '${DateFormat('MMM dd, yyyy').format(tour.startDate!)} - ${DateFormat('MMM dd, yyyy').format(tour.endDate ?? tour.startDate!)}',
                    style: const pw.TextStyle(fontSize: 12),
                  ),
                ),
                pw.SizedBox(height: 24),
                pw.Divider(),
                pw.SizedBox(height: 12),
                
                pw.Row(
                  mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                  children: [
                    pw.Text('Total Tour Cost:', style: pw.TextStyle(fontWeight: pw.FontWeight.bold)),
                    pw.Text('${totalCost.toStringAsFixed(2)} BDT'),
                  ],
                ),
                pw.SizedBox(height: 24),

                pw.Text('MEMBER CONTRIBUTIONS', style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold)),
                pw.SizedBox(height: 8),
                pw.TableHelper.fromTextArray(
                  headers: ['Name', 'Paid', 'Share', 'Balance'],
                  data: users.map<List<String>>((u) {
                    final paid = expenses.where((e) => e.payerId == u.id).fold(0.0, (sum, e) => sum + e.amount);
                    final share = splits.where((s) => s.userId == u.id).fold(0.0, (sum, s) => sum + s.amount);
                    final balance = paid - share;
                    return [
                      u.name,
                      paid.toStringAsFixed(0),
                      share.toStringAsFixed(0),
                      '${balance >= 0 ? '+' : ''}${balance.toStringAsFixed(0)}',
                    ];
                  }).toList(),
                ),
                
                pw.SizedBox(height: 24),
                pw.Text('SETTLEMENT PLAN', style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold)),
                pw.SizedBox(height: 8),
                ...settlementInstructions.map((s) => pw.Text('• ${s.payerName} pays ${s.amount.toStringAsFixed(0)} to ${s.receiverName}')),
                
                pw.Spacer(),
                pw.Divider(),
                pw.Center(
                  child: pw.Text('Generated by Tour Manager App', style: pw.TextStyle(fontSize: 10, color: PdfColors.grey)),
                ),
              ],
            ),
          );
        },
      ),
    );

    await Printing.layoutPdf(onLayout: (PdfPageFormat format) async => pdf.save());
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text("Final Statement"),
        actions: [
          IconButton(
            icon: const Icon(Icons.print),
            onPressed: _printReceipt,
          )
        ],
      ),
      body: SingleChildScrollView(
        child: Column(
          children: [
            const SizedBox(height: 20),
            _buildReceiptPaper(context),
            const SizedBox(height: 40),
            Padding(
              padding: const EdgeInsets.symmetric(horizontal: 24),
              child: SizedBox(
                width: double.infinity,
                child: FilledButton.icon(
                  onPressed: _printReceipt,
                  icon: const Icon(Icons.picture_as_pdf),
                  label: const Text("Print / Save as PDF"),
                  style: FilledButton.styleFrom(
                    padding: const EdgeInsets.symmetric(vertical: 16),
                    shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
                  ),
                ),
              ),
            ),
            const SizedBox(height: 40),
          ],
        ),
      ),
    );
  }

  Widget _buildReceiptPaper(BuildContext context) {
    final totalCost = expenses.fold(0.0, (sum, e) => sum + e.amount);

    return Container(
      margin: const EdgeInsets.symmetric(horizontal: 24),
      padding: const EdgeInsets.all(24),
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(4),
        boxShadow: [
          BoxShadow(color: Colors.black.withOpacity(0.1), blurRadius: 10, spreadRadius: 2),
        ],
      ),
      child: Column(
        children: [
          const Text("FINAL RECEIPT", style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold, letterSpacing: 2)),
          const SizedBox(height: 4),
          const Divider(),
          const SizedBox(height: 12),
          Text(tour.name, style: const TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
          Text(
            tour.startDate == null 
                ? 'Active Adventure' 
                : '${DateFormat('MMM dd, yyyy').format(tour.startDate!)} - ${DateFormat('MMM dd, yyyy').format(tour.endDate ?? tour.startDate!)}',
            style: const TextStyle(fontSize: 12, color: Colors.grey),
          ),
          const SizedBox(height: 24),
          _buildRow("Total Tour Cost", "${totalCost.toStringAsFixed(0)} ৳", isBold: true),
          _buildRow("Total Members", "${users.length}"),
          const SizedBox(height: 24),
          const Align(alignment: Alignment.centerLeft, child: Text("CONTRIBUTIONS", style: TextStyle(fontWeight: FontWeight.bold, fontSize: 12))),
          const SizedBox(height: 8),
          ...users.map((u) {
            final paid = expenses.where((e) => e.payerId == u.id).fold(0.0, (sum, e) => sum + e.amount);
            final share = splits.where((s) => s.userId == u.id).fold(0.0, (sum, s) => sum + s.amount);
            final balance = paid - share;
            return Padding(
              padding: const EdgeInsets.only(bottom: 4),
              child: Row(
                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                children: [
                  Text(u.name, style: const TextStyle(fontSize: 14)),
                  Text(
                    "${paid.toStringAsFixed(0)} ৳  (${balance >= 0 ? '+' : ''}${balance.toStringAsFixed(0)})",
                    style: TextStyle(fontSize: 13, color: balance >= 0 ? Colors.green : Colors.red),
                  ),
                ],
              ),
            );
          }),
          const SizedBox(height: 24),
          const Align(alignment: Alignment.centerLeft, child: Text("FINAL SETTLEMENT", style: TextStyle(fontWeight: FontWeight.bold, fontSize: 12))),
          const SizedBox(height: 8),
          ...settlementInstructions.map((s) => Padding(
            padding: const EdgeInsets.only(bottom: 6),
            child: Row(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                const Icon(Icons.circle, size: 6, color: Colors.teal),
                const SizedBox(width: 8),
                Expanded(child: Text("${s.payerName} pays ${s.amount.toStringAsFixed(0)} ৳ to ${s.receiverName}", style: const TextStyle(fontSize: 13))),
              ],
            ),
          )),
          const SizedBox(height: 40),
          const Opacity(
            opacity: 0.3,
            child: Text("Thank you for using Tour Manager", style: TextStyle(fontSize: 10, fontStyle: FontStyle.italic)),
          ),
          const SizedBox(height: 10),
          _buildZigZagBottom(),
        ],
      ),
    );
  }

  Widget _buildRow(String label, String value, {bool isBold = false}) {
    return Padding(
      padding: const EdgeInsets.only(bottom: 8),
      child: Row(
        mainAxisAlignment: MainAxisAlignment.spaceBetween,
        children: [
          Text(label, style: TextStyle(fontSize: 14, fontWeight: isBold ? FontWeight.bold : FontWeight.normal)),
          Text(value, style: TextStyle(fontSize: 14, fontWeight: isBold ? FontWeight.bold : FontWeight.bold, color: isBold ? Colors.teal : Colors.black)),
        ],
      ),
    );
  }

  Widget _buildZigZagBottom() {
    return Row(
      children: List.generate(20, (index) => Expanded(
        child: Container(
          height: 10,
          decoration: BoxDecoration(
            color: Colors.grey.shade100,
            borderRadius: const BorderRadius.only(
              bottomLeft: Radius.circular(5),
              bottomRight: Radius.circular(5),
            ),
          ),
        ),
      )),
    );
  }
}
